# -*- coding: utf-8 -*-
"""Basis, Orthogonal, and Orthonormal Vectors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pqgvc7WMuhbMs-POGJrRb9v5aR0pKEBj

Nomor 1
"""

import numpy as np

# buat vector i dengan elemen (1,0)
i = np.array([1, 0])
i

# dan vector j dengan elemen (0,1)
j = np.array([0, 1])
j

# buktikan bahwa vector i dan vector j itu orthogonal
bukti1 = np.dot(i, j)

if bukti1 == 0:
    print("Jadi i dan j adalah orthogonal karena secara matematisnya juga (1, 0) . (0, 1) = (1 x 0) + (0 x 1) =", bukti1)
else:
    print("i dan j bukan orthogonal karena hasil akhirnya", bukti1)

"""Nomor 2"""

# Bagaimana dengan v=(1,2) dan w=(2,-1), apakah juga orthogonal?
v = np.array([1, 2])
w = np.array([2, -1])

bukti2 = np.dot(v, w)

if bukti2 == 0:
    print("v dan w juga orthogonal, karena hasil akhirnya:", bukti2)
else:
    print("v dan w bukan orthogonal karena hasil akhirnya:", bukti2)