# -*- coding: utf-8 -*-
"""Exercises on Algebra Data Structures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESUcgMYeFB-ZSVMRoJkasISs1uUq5zmz

Nomor 1
"""

import numpy as np

# selesaikan soal (transpose) berikut
# What is the transpose of this vector?
# [25]
# [2]
# [-3]
# [-23]

x = np.array([[25],
              [2],
              [-3],
              [-23]])
x
x_t = x.T
print("Transpos dari matrik x: ",x_t)