# -*- coding: utf-8 -*-
"""Generic Tensor Notation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z2QSQL3P332B1qfhwmotTKN3_dHZMLdm

Nomor 1
"""

import torch
import tensorflow as tf

# jelaskan tentang perintah ini
# images_pt = torch.zeros([32, 28, 28, 3])
images_pt = torch.zeros([32, 28, 28, 3])
images_pt

"""
PENJELASAN

1. torch.zeros(...)
- Digunakan untuk membuat tensor yang seluruh elemennya bernilai 0
- Artinya setiap isi tensor otomatis terisi angka nol

2. [32, 28, 28, 3]
- 32 : Banyaknya data (umumnya jumlah gambar / batch size)
- 28 : Tinggi gambar (height)
- 28 : Lebar gambar (width)
- 3 : Jumlah channel warna (RGB)

Kesimpulannya, perintah tersebut membuat 32 gambar kosong dengan spesifikasi:
- ukuran 28 x 28 pixel
- memiliki 3 channel warna (RGB)
- seluruh nilai pixel bernilai 0 (hitam)

Hal ini menyebabkan semua output yang dihasilkan berupa 0, karena tensor dibuat menggunakan fungsi torch.zeros().
"""