# -*- coding: utf-8 -*-
"""Matrix Tensors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5OHE2PJRUw3xhvzgcbsh_5IdPMzmV1Y

Nomor 1
"""

import numpy as np

# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[2, 4, 6],
              [3, 5, 7]])
print(X)

# tampilkan ukuran dari matrix X
X.shape

# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

#tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

"""Nomor 2

Ulangi soal nomor 1 menggunakan pytorch
"""

import torch

# buat matrix X berukuran 2x3 menggunakan torch
X_pt = torch.tensor([[2, 4, 6],
                      [3, 5, 7]])
print(X_pt)

# tampilkan ukuran dari matrix X_pt
X_pt.shape

# tampilkan seluruh elemen dari kolom pertama dari matrix X_pt
X_pt[:,0]

#tampilkan seluruh elemen dari baris kedua dari matrix X_pt
X_pt[1,:]

"""Ulangi soal nomor 1 menggunakan tensorflow"""

import tensorflow as tf

# buat matrix X berukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[2, 4, 6],
                      [3, 5, 7]])
X_tf

# tampilkan ukuran dari matrix X_tf
tf.shape(X_tf)

# tampilkan seluruh elemen dari kolom pertama dari matrix X_tf
X_tf[:,0]

#tampilkan seluruh elemen dari baris kedua dari matrix X_tf
X_tf[1,:]