# -*- coding: utf-8 -*-
"""Norms and Unit Vectors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_pLGuM4bDqUIFVmk5tiBfVphWet7d72

Nomor 1
"""

import numpy as np

# buat vector x dengan ukuran 3x1
x = np.array([[1],
              [2],
              [3]])
x

# hitung nilai L2 norm dari vector x
(1**2 + 2**2 + 3**2)**(1/2)

"""Nomor 2"""

# buat vector v dengan elemen (3,4)
v = np.array([3, 4])
print("Vektor asli:",v)

# hitung nilai L2 norm dari vector v
norm = np.linalg.norm(v)
print("Panjang vektor:", norm)

# tampilkan unit vector dari vector v
unit_v = v / norm
print("Unit vector:", unit_v)

# hitung panjang unit vector dari vector v
print("Panjang unit vector:", np.linalg.norm(unit_v))