# -*- coding: utf-8 -*-
"""Scalar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EYn9Ym9OLA3BKwIHzeSfjvwJBMQ-EsF6

Nomor 1
"""

# buat variabel skalar x dan simpan suatu nilai skalar
x = 100
print("Nilai x:",x)

# tampilkan tipe data dari x
print("Tipe data x:", type(x))

# buat variabel skalar y dan simpan suatu nilai skalar
y = 50
print("Nilai y:",y)

# tampilkan tipe data dari y
print("Tipe data y:", type(y))

# jumlahkan x + y
sum = x + y
print("Hasil dari x + y:", sum)

# buat variabel bernama x_float dan simpan suatu nilai desimal
x_float = 0.25
print("Nilai x_float:", x_float)

# jumlahkan x_float dengan y
sum2 = x_float + y
print("Hasil dari x_float + y:", sum2)

# tampilkan tipe data dari x_float
print("Tipe data x_float:", type(x_float))

"""Nomor 2, Lakukan tahapan pada soal 1 dengan menggunakan tensorflow"""

import tensorflow as tf

# buat variabel skalar x_tf dan simpan suatu nilai skalar
x_tf = tf.Variable(100, dtype=tf.int16)
print("Nilai x_tf:",x_tf)

# tampilkan bentuk dan tipe data dari x_tf
print("Bentuk data x_tf:",x_tf.shape)
print("Tipe data x_tf:",type(x_tf))

# buat variabel skalar y_tf dan simpan suatu nilai skalar
y_tf = tf.Variable(50, dtype=tf.int16)
print("Nilai y_tf:",y_tf)

# tampilkan bentuk dan tipe data dari y_tf
print("Bentuk data y_tf:",y_tf.shape)
print("Tipe data y_tf:",type(y_tf))

# jumlahkan x_tf + y_tf
tf_sum1 = x_tf + y_tf
print("Hasil dari x_tf + y_tf:",tf_sum1)

tf_sum2 = tf.add(x_tf, y_tf)
print("Hasil dari x_tf + y_tf:",tf_sum2)

print("Hasil dari x_tf + y_tf:",tf_sum.numpy())

# buat variabel bernama tf_float dan simpan suatu nilai desimal
tf_float = tf.Variable(0.25, dtype=tf.float16)
print("Nilai tf_float:",tf_float)

# jumlahkan tf_float dengan y
sum_float = tf_float + y
print("Hasil dari tf_float + y:",sum_float)

# tampilkan bentuk dan tipe data dari tf_float
print("Bentuk data tf_float:",tf_float.shape)
print("Tipe data tf_float:",type(tf_float))

"""Nomor 3, Lakukan tahapan pada soal 1 dengan menggunakan pytorch"""

import torch

# buat variabel skalar x_pt dan simpan suatu nilai skalar
x_pt = torch.tensor(100)
print("Nilai x_pt:",x_pt)

# tampilkan bentuk dan tipe data dari x_pt
print("Bentuk data x_pt:",x_pt.shape)
print("Tipe data x_pt:",type(x_pt))

# buat variabel skalar y_pt dan simpan suatu nilai skalar
y_pt = torch.tensor(50)
print("Nilai y_pt:",y_pt)

# tampilkan tipe data dari y_pt
print("Bentuk data y_pt:",y_pt.shape)
print("Tipe data y_pt:",type(y_pt))

# jumlahkan x_pt + y_pt
sum_pt = x_pt + y_pt
print("Hasil dari x_pt + y_pt:",sum_pt)

# buat variabel bernama pt_float dan simpan suatu nilai desimal
pt_float = torch.tensor(0.25)
print("Nilai pt_float:",pt_float)

# jumlahkan pt_float dengan y
sum_floatpt = pt_float + y_pt
print("Hasil dari pt_float + y_pt:",sum_floatpt)

# tampilkan tipe data dari pt_float
print("Bentuk data pt_float:",pt_float.shape)
print("Tipe data pt_float:",type(pt_float))