# -*- coding: utf-8 -*-
"""Vectors and Vector Transposition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13P5jzqO0mGLb77fG7vBkP5w7C7mhPmom

Nomor 1
"""

import numpy as np

# buat vector x dengan ukuran 3x1
x = np.array([[1],
              [2],
              [3]])
print("Vektor x:\n",x)

# hitung panjang vector x
print("Panjang vektor x:",len(x))

# tampilkan ukuran vector x
print("Ukuran vektor x:",x.shape)

# tampilkan tipe data dari vector x
print("Tipe data vektor x:",type(x))

# akses elemen pertama dari vector x
print("Elemen pertama vektor x:",x[0])

# tampilkan tipe data elemen pertama dari vector x
print("Tipe data elemen pertama vektor x:",type(x[0]))

"""Nomor 2"""

# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

# tampilkan ukuran dari vector x_t
x_t.shape

# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[12, 14, 16]])
y_t = y.T
y_t

# tampilkan ukuran dari vector y_t
y_t.shape

"""Nomor 3

Lakukan soal nomor 2 menggunakan pytorch
"""

import torch

# lakukan transpose pada vector x dan simpan pada variabel x_pt
x_pt = torch.tensor([[1],
                    [2],
                    [3]])
x_pt = x.T
x_pt

# tampilkan ukuran dari vector x_pt
x_pt.shape

# lakukan transpose pada vector y dan simpan pada variabel y_pt
y_pt = tf.Variable([12, 14, 16])
y_pt = y.T
y_pt

# tampilkan ukuran dari vector y_pt
y_pt.shape

"""Lakukan soal nomor 2 menggunakan tensorflow"""

import tensorflow as tf

# lakukan transpose pada vector x dan simpan pada variabel x_tf
x_tf = tf.constant([[1],
                   [2],
                   [3]])
x_tf = x.T
x_tf

# tampilkan ukuran dari vector x_tf
x_tf.shape

# lakukan transpose pada vector y dan simpan pada variabel y_tf
y_tf = tf.Variable([12, 14, 16])
y_tf = y.T
y_tf

# tampilkan ukuran dari vector y_tf
y_tf.shape