# -*- coding: utf-8 -*-
"""Basic Tensor Arithmetic (The Hadamard Product.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJHgEjaNfRVd0wzHN81SyFp42jKcspEZ

Nomor 1
"""

import numpy as np
import torch as pt
import tensorflow as tf

# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[10, 20, 30], [15, 20, 45]])
print(X)

# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = pt.tensor([[10, 20, 30], [15, 30, 45]])
print(X_pt)

# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[10, 20, 30], [15, 30, 45]])
print(X_tf)

# lakukan perkalian matrix X, X_pt dan X_tf dengan suatu skalar
print(X * 2)
print("\n", X_pt * 2)
print("\n", X_tf * 2)

# lakukan penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar
print(X + 10)
print("\n", X_pt + 10)
print("\n", X_tf + 10)

# lakukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar
print(X - 5)
print("\n", X_pt - 5)
print("\n", X_tf - 5)

"""Nomor 2"""

# buat matrix Y dengan ukuran 2x3 menggunakan numpy
Y = np.array([[20, 40, 50], [30, 60, 90]])
print(Y)

# buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch
Y_pt = pt.tensor([[20, 30, 40], [30, 60, 90]])
print(Y_pt)

# buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow
Y_tf = tf.Variable([[20, 30, 40], [30, 60, 90]])
print(Y_tf)

# kalikan matrix X dengan Y
print(X * Y)

# kalikan matrix X_pt dengan Y_pt
print(X_pt * Y_pt)

# kalikan matrix X_tf dengan Y_tf
print(X_tf * Y_tf)