# -*- coding: utf-8 -*-
"""Tensor Reduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xQo9To4bG6ZYhu_dCTdzDByGECTVobZO
"""

import numpy as np
import torch as pt
import tensorflow as tf

"""Nomor 1"""

# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[10, 20, 30], [15, 30, 45]])
print(X)

# hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
print(X.sum())

# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[10, 20, 30], [15, 30, 45]])
print(X_tf)

# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = pt.tensor([[10, 20, 30], [15, 30, 45]])
print(X_pt)

"""Nomor 2"""

# hitung hasil penjumlahan seluruh elemen matrix X
print(X.sum())

# hitung hasil penjumlahan seluruh elemen matrix X_pt
print(pt.sum(X_pt))

# hitung hasil penjumlahan seluruh elemen matrix X_tf
print(tf.reduce_sum(X_tf))

"""Nomor 3"""

# hitung hasil penjumlahan matrix X berdasarkan row nya
print(np.sum(X, axis=1))

# hitung hasil penjumlahan matrix X_pt berdasarkan row nya
print(pt.sum(X_pt, axis=1))

# hitung hasil penjumlahan matrix X_tf berdasarkan row nya
print(tf.reduce_sum(X_tf, axis=1))

"""Nomor 4"""

# hitung hasil penjumlahan matrix X berdasarkan kolom nya
print(np.sum(X, axis=0))

# hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
print(pt.sum(X_pt, axis=0))

# hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya
print(tf.reduce_sum(X_tf, axis=0))

"""Nomor 5"""

# hitung nilai minimal dari matrix X, X_pt dan X_tf
X_min = np.min(X)
X_pt_min = pt.min(X_pt)
X_tf_min = tf.reduce_min(X_tf)
print(f"Nilai minimal dari X Adalah : {X_min}")
print(f"Nilai minimal dari X_pt Adalah : {X_pt_min}")
print(f"Nilai minimal dari X_tf Adalah : {X_tf_min.numpy()}")

# hitung nilai maksimal dari matrix X, X_pt dan X_tf
X_max = np.max(X)
X_pt_max = pt.max(X_pt)
X_tf_max = tf.reduce_max(X_tf)
print(f"Nilai maksimal dari X Adalah : {X_max}")
print(f"Nilai maksimal dari X_pt Adalah : {X_pt_max}")
print(f"Nilai maksimal dari X_tf Adalah : {X_tf_max.numpy()}")

# hitung nilai rata-rata dari matrix X, X_pt dan X_tf
X_pt = X_pt.float()
X_mean = np.mean(X)
X_pt_mean = pt.mean(X_pt)
X_tf_mean = tf.reduce_mean(X_tf)
print(f"Nilai Rata-Rata dari X Adalah : {X_mean}")
print(f"Nilai Rata-Rata dari X_pt Adalah : {X_pt_mean}")
print(f"Nilai Rata-Rata dari X_tf Adalah : {X_tf_mean.numpy()}")

"""Nomor 6"""

# hitung hasil perkalian seluruh elemen matrix X
print(X.prod())

# hitung hasil perkalian seluruh elemen matrix X_pt
print(pt.prod(X_pt))

# hitung hasil perkalian seluruh elemen matrix X_tf
print(tf.reduce_prod(X_tf))