# -*- coding: utf-8 -*-
"""Tensor Transposition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPnMInhtJ4q3i6TjerC5Ugr3u7rs7Zlh

Nomor 1
"""

# buat matrix X dengan ukuran 2x3 menggunakan numpy
import numpy as np

X = np.array([[10, 20, 30], [15, 30, 45]])
print(X)

# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
import torch as pt

X_pt = pt.tensor([[10, 20, 30], [15, 30, 45]])
print(X_pt)

# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
import tensorflow as tf

X_tf = tf.Variable([[10, 20, 30], [15, 30, 45]])
print(X_tf)

"""Nomor 2"""

# lakukan transpose pada matrix X
X_trans = X.T
print(X_trans)

# lakukan transpose pada matrix X_pt
X_pt_trans = X_pt.T
print("\n", X_pt_trans)
# lakukan transpose pada matrix X_tf
X_tf_trans = tf.transpose(X_tf)
print("\n", X_tf_trans)