# -*- coding: utf-8 -*-
"""Visualizing Linear Systems.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K8LFUnAj976xBt6nRF6iszyYZVnkyPbS

Buat visualisasi dari persamaan berikut:
$$ y = 2x+1  $$ $$ 3x-y = 5 $$

Ubah persamaan kedua dalam bentuk persamaan y
$$ 3x - y = 5 $$
$$ - y = 5 - 3x $$
$$  y = 3x + 5 $$
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-10, 5, 200)
y1 = 2 * x + 1
y2 = 3 * x + 5
fig, ax = plt.subplots()
plt.xlabel('x')
plt.ylabel('y')
ax.plot(x, y1, c='green')
ax.plot(x, y2, c='brown')
plt.axvline(x=6, color='purple', linestyle='--')
plt.axhline(y=13, color='purple', linestyle='--')
plt.grid()
plt.show()